### ISSUE TITLE
GnomeDesktop dependence

### ISSUE THREAD

**Issue by tigersharke** [tigersharke/lutris-freebsd#1]
Builds but run fails with error regarding dependence upon GnomeDesktop.

% lutris
Traceback (most recent call last):
  File "/usr/local/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/local/lib/python3.9/site-packages/lutris/gui/application.py", line 31, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/local/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available

**Comment by tigersharke** [comment]
Fixed by adding gnomedesktop3 to USE_GNOME.
