### ISSUE TITLE
ModuleNotFoundError: No module named 'dbus'

### ISSUE THREAD

**Issue by tigersharke** [tigersharke/lutris-freebsd#2]
This seems to be a python module for dbus that I need to find?
 
% lutris
2021-09-29 00:41:58,730: Unsupported architecture amd64
ldconfig: illegal option -- p
usage: ldconfig [-32] [-elf] [-Rimrsv] [-f hints_file] [directory | file ...]
2021-09-29 00:41:58,754: ['/sbin/ldconfig', '-p'] command failed: Command '['/sbin/ldconfig', '-p']' returned non-zero exit status 1.
2021-09-29 00:41:58,755: No GPU available on this system!
Traceback (most recent call last):
  File "/usr/local/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/local/lib/python3.9/site-packages/lutris/gui/application.py", line 39, in <module>
    from lutris.game import Game
  File "/usr/local/lib/python3.9/site-packages/lutris/game.py", line 16, in <module>
    from lutris.config import LutrisConfig
  File "/usr/local/lib/python3.9/site-packages/lutris/config.py", line 8, in <module>
    from lutris import settings, sysoptions
  File "/usr/local/lib/python3.9/site-packages/lutris/sysoptions.py", line 9, in <module>
    from lutris.util.display import DISPLAY_MANAGER, SCREEN_SAVER_INHIBITOR, USE_DRI_PRIME
  File "/usr/local/lib/python3.9/site-packages/lutris/util/display.py", line 19, in <module>
    from lutris.util.graphics.displayconfig import MutterDisplayManager
  File "/usr/local/lib/python3.9/site-packages/lutris/util/graphics/displayconfig.py", line 4, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

**Comment by tigersharke** [comment]
Various dependencies were absent though not drawn as dependencies.  www/webkit2-gtk3 seems to fail in pulling libsoup and its makefile lacks a bunch of stuff noticed by make.conf toggle DEVELOPER=yes.  Once webkit succeeded its build and install, libsoup was reinstalled fresh, and some depends or other adjustments made to the lutris makefile, the error is gone and lutris runs.
